cop:
   image: lhaskins/fabric-cop:latest
   ports:
     - "8888:8888"
     - "53:53/udp"
   command: sh -c 'cop server start -ca ~/.cop/ec.pem -ca-key ~/.cop/ec-key.pem -config /config/cop.json -address "0.0.0.0"'
orderer:
  image: lhaskins/fabric-orderer
  environment:
    - ORDERER_GENERAL_LEDGERTYPE=ram
    - ORDERER_GENERAL_BATCHTIMEOUT=10s
    - ORDERER_GENERAL_BATCHSIZE=10
    - ORDERER_GENERAL_MAXWINDOWSIZE=1000
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_RAMLEDGER_HISTORY_SIZE=100
    - ORDERER_GENERAL_ORDERERTYPE=solo
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
  command: orderer
  ports:
    - 5151:7050
couchdb0:
  image: klaemo/couchdb:2.0.0
  command: tini -- /docker-entrypoint.sh /opt/couchdb/bin/couchdb
  ports:
    - 5984:5984
couchdb1:
  image: klaemo/couchdb:2.0.0
  command: tini -- /docker-entrypoint.sh /opt/couchdb/bin/couchdb
  ports:
    - 5985:5984
vp0:
  image: lhaskins/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
    - CORE_NEXT=true
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_ID=vp0
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
  volumes:
      - /var/run/:/host/var/run/
  command: peer node start
  links:
    - orderer
    - cop
    - couchdb0
  ports:
    - 7051:7051
vp1:
  image: lhaskins/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
    - CORE_NEXT=true
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_ID=vp1
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
  volumes:
      - /var/run/:/host/var/run/
  command: peer node start
  links:
    - orderer
    - cop
    - couchdb1
    - vp0
  ports:
    - 7056:7051
