vp2:
  image: lhaskins/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
    - CORE_NEXT=true
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_ID=vp2
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_COMMITTER_LEDGER_ORDERER=172.17.0.2:7050
    - CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.5:7051
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=172.17.0.3:5984
  volumes:
      - /var/run/:/host/var/run/
      #- /hyperledger/cop-setup:/opt/cop-setup
  command: peer node start
  ports:
    - 7052:7051
